title: Causal Inference Augmented Reflection for Long-Term Planning via LLMs
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
description: ICRA 2025<br/>Tuocheng Hu, Jiatao Zhang, Yufan Song, Wei Song, Shiqiang Zhu1
